name: running test, build image, push registry, deploy
on:
  push:
    branches:
      - main
jobs:
  running-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: run test
        run: go test -v ./... -cover
      - run: go version

  buildimage:
    name: build image
    runs-on: ubuntu-latest
    needs: running-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build image
        run: docker build -t mifthahuddin/cicd-go:latest .
      - name : login registry
        run : docker login
        uses : docker/login-action@v2
        with :
          username : ${{ secrets.DOCKER_USERNAME }}
          password : ${{ secrets.DOCKER_PASSWORD }}
      - name : push image
        run : docker push mifthahuddin/cicd-go:latest

  deploy:
    name: deploy ec2
    runs-on: ubuntu-latest
    needs: buildimage
    steps:
      - uses: actions/checkout@v2
      - name: deploy ec2
        uses: appleboy/ssh-action@master
    with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ec2-user/cicd-go
          docker-compose down
          docker-compose up -d
          
  








